### ISSUE TITLE
figures_captions_list() is returning an empty figure list

### ISSUE THREAD

**Issue by vipulg13** [uic-evl/curation-pipeline#4]
Dear @jtrells, dear @pengyuanli,

thanks for providing this high level API to the PDFigCapX project module. Unfortunately, I am running into issues. The code is running without any error, however, the figures_captions_list() function is returning a list of empty figures for every page in all cases. I tried debugging the code and found that something is amiss in the bounding box detection logic. There could be multiple reasons for not getting the desirable result, e.g., different versions of dependencies (external binaries), or python modules. For your information, I am using the below set of versions:

Operating System: Windows x64
Python environment: 2.7
xpdf-tools-win-4.03
ImageMagick-7.1.0-portable-Q16-x64
opencv-2.4.11
chrome driver-99.0.4844.17

since pdftohtml requires ghostscript, I had to copy the ghostcript executables from python 3.X environment to 2.7, as I was not able to find executables under path ./Library/bin in python 2.7 despite successful installation.

Could you please either share the exact versions of binaries used in the script, or convert this monolith pipeline into a microservices architecture (supporting REST endpoints and a docker image)? The latter has its benefits, as the end users will not have to deal with such dependencies. 
Your help would be much appreciated!

Regards,
Vipul

PS: If required, I could also contribute to the development of the same.

**Comment by jtrells** [comment]
Hi Vipul, 

There are some known detection issues when the annotation layer is not well aligned with the background. I'm slowly trying to migrate the original library to python3 and solve those issues. You can find the repository here https://github.com/pengyuanli/PDFigCapX . Also, if you can share any PDF giving you issues, that would be very helpful.

About the binaries:
Could you check the python3 branch? That branch has a Dockerfile to create a sandbox environment.
Although most of the code uses Python3, it calls 2.7 version of the PdfFigCapX binaries.

**Comment by vipulg13** [comment]
Dear @jtrells ,

thanks for your reply and sharing the information. I was aware of  [this](https://github.com/pengyuanli/PDFigCapX), but unfortunately I missed the python3 branch. 

You will find an exemplary PDF document in the attachment. The demo version, provided [here](https://www.eecis.udel.edu/~compbio/PDFigCapX) works flawlessly.
[10_1007_s11661_997_0115_5.pdf](https://github.com/uic-evl/curation-pipeline/files/8094021/10_1007_s11661_997_0115_5.pdf)
 
I will try setting up a new conda environment taking reference of Dockerfile and try to run the script again. 

It would be great if you could let me know your findings on the provided PDF document.

**Comment by vipulg13** [comment]
Dear @jtrells ,

thanks for your reply and sharing the information. I was aware of  [this](https://github.com/pengyuanli/PDFigCapX) repository, but unfortunately I missed the python3 branch. 

You could use [10_1007_s11661_997_0115_5.pdf](https://github.com/uic-evl/curation-pipeline/files/8094021/10_1007_s11661_997_0115_5.pdf) to reproduce the issue. FYI- the demo version, provided [here](https://www.eecis.udel.edu/~compbio/PDFigCapX) works flawlessly.
I will try setting up a new conda environment (following the instruction from the Dockerfile) and run the script again. 

It would be great if you could let me know your findings on the provided PDF document.

**Comment by vipulg13** [comment]
Dear @jtrells ,

do you have any update on this issue? I tried setting up a new conda environment, but the problem still persists.

**Comment by vipulg13** [comment]
Dear @jtrells, @pengyuanli, after making a few changes in the Dockerfile and the code from "python3" branch, the figcapx functionality worked as expected. Furthermore, I have exposed this python project as REST api using flask, and dockerized it. The docker image can be pulled/ run by executing the following commands: 

`docker pull vipulg13/pdfigcapx`
`docker run -p 9000:9000 -ti -d --name pdfigcapx vipulg13/pdfigcapx:0.1`

Also, I have written a very basic client api to interact with the service. Please find the same below:

```python
def pdfigcapx_service_client(pdf_path, output_dir_path):
    url = "http://localhost:9000/pdfigcapxprocess"
    fname = Path(pdf_path).name
    files = {
        "file": (
            fname,
            open(pdf_path, "rb"),
            "application/pdf",
        )
    }
    try:
        r = requests.post(url, files=files, timeout=120)
        r.raise_for_status()
        if "Content-Disposition" in r.headers:
            filename = r.headers["Content-Disposition"].split("filename=")[-1]
            filename = os.path.join(output_dir_path, filename)
            with open(filename, "wb") as f:
                f.write(r.content)
        else:
            print("attachment not found")
    except requests.exceptions.RequestException as e:
        print(e, file=sys.stderr)
´´´
